COLLECTOR = "eth"
CHAIN_NAME = "ETH"
DASHBOARD_DEFAULT_CHAIN = "ETH"
SCORE_ALERT_THRESHOLD = 50

# ETH – pode listar várias URLs separadas por vírgula (fallback)
ETH_RPC_URL = "https://ethereum.publicnode.com,https://eth.llamarpc.com,https://cloudflare-eth.com"
ETH_BLOCKS_BACK = 20
ETH_MAX_TX = 50
ETH_ONLY_ERC20 = true
ETH_INCLUDE_ETH_VALUE_MIN = 0.0

# Telegram (opcional)
TELEGRAM_BOT_TOKEN = ""
TELEGRAM_CHAT_ID = ""