# Várias URLs separadas por vírgula (recomendado)
ETH_RPC_URL = "https://ethereum.publicnode.com,https://eth.llamarpc.com,https://cloudflare-eth.com"
# Quantos blocos recentes ler e limite de transações
ETH_BLOCKS_BACK = "20"
ETH_MAX_TX = "50"
# Filtragem (opcional)
ETH_ONLY_ERC20 = "false"
ETH_INCLUDE_ETH_VALUE_MIN = "0.2"

SCORE_ALERT_THRESHOLD = "50"
CHAIN_NAME = "ETH"

# Telegram (opcional)
TELEGRAM_BOT_TOKEN = ""
TELEGRAM_CHAT_ID = ""
